#!/bin/bash

GPIO_OP_1=22
GPIO_OP_2=23
GPIO_OP_3=24
GPIO_OP_4=25
GPIO_OP_5=26
GPIO_OP_6=27
GPIO_OP_7=16

GPIO_IP_1=6
GPIO_IP_2=7
GPIO_IP_3=10
GPIO_IP_4=11

GPIO_EXPORT="/sys/class/gpio/export"

function prob_i2cdev_driver
{
   modprobe i2c-dev
}

function export_gpios
{
   # Export GPIO For Output Pins
   echo ${GPIO_OP_1} > ${GPIO_EXPORT}  
   echo ${GPIO_OP_2} > ${GPIO_EXPORT}
   echo ${GPIO_OP_3} > ${GPIO_EXPORT}
   echo ${GPIO_OP_4} > ${GPIO_EXPORT}
   echo ${GPIO_OP_5} > ${GPIO_EXPORT}
   echo ${GPIO_OP_6} > ${GPIO_EXPORT}
   echo ${GPIO_OP_7} > ${GPIO_EXPORT}

   # Export GPIO For Input Pins
   echo ${GPIO_IP_1} > ${GPIO_EXPORT}  
   echo ${GPIO_IP_2} > ${GPIO_EXPORT}
   echo ${GPIO_IP_3} > ${GPIO_EXPORT}
   echo ${GPIO_IP_4} > ${GPIO_EXPORT}
}

function stop {
   echo "Stopping users setup script...!"
}

function start {
   export_gpios
   # prob_i2cdev_driver
}

function restart {
   export_gpios
   # prob_i2cdev_driver
}

function status {
   echo "No Status from users setup script...!"
}

case "$1" in
   start)
      start
   ;;
   stop)
      stop
   ;;
   restart)
      restart
   ;;
   status)
      status
   ;;
   *)
      echo "Usage: $0 {start|stop|restart|status}"
esac